# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 895)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.btnSearchDevices = QtWidgets.QPushButton(self.centralWidget)
        self.btnSearchDevices.setGeometry(QtCore.QRect(240, 20, 311, 71))
        self.btnSearchDevices.setObjectName("btnSearchDevices")
        self.grbKeys1 = QtWidgets.QGroupBox(self.centralWidget)
        self.grbKeys1.setGeometry(QtCore.QRect(20, 120, 361, 151))
        self.grbKeys1.setObjectName("grbKeys1")
        self.btnKeys1_mid = QtWidgets.QPushButton(self.grbKeys1)
        self.btnKeys1_mid.setGeometry(QtCore.QRect(10, 30, 161, 51))
        self.btnKeys1_mid.setObjectName("btnKeys1_mid")
        self.btnKeys1_high = QtWidgets.QPushButton(self.grbKeys1)
        self.btnKeys1_high.setGeometry(QtCore.QRect(190, 31, 161, 51))
        self.btnKeys1_high.setObjectName("btnKeys1_high")
        self.btnKeys1_bat = QtWidgets.QPushButton(self.grbKeys1)
        self.btnKeys1_bat.setGeometry(QtCore.QRect(10, 90, 161, 51))
        self.btnKeys1_bat.setObjectName("btnKeys1_bat")
        self.lneKeys1_bat = QtWidgets.QLineEdit(self.grbKeys1)
        self.lneKeys1_bat.setGeometry(QtCore.QRect(190, 90, 161, 51))
        self.lneKeys1_bat.setAlignment(QtCore.Qt.AlignCenter)
        self.lneKeys1_bat.setReadOnly(True)
        self.lneKeys1_bat.setObjectName("lneKeys1_bat")
        self.grbKeys2 = QtWidgets.QGroupBox(self.centralWidget)
        self.grbKeys2.setGeometry(QtCore.QRect(410, 120, 361, 151))
        self.grbKeys2.setObjectName("grbKeys2")
        self.btnKeys2_mid = QtWidgets.QPushButton(self.grbKeys2)
        self.btnKeys2_mid.setGeometry(QtCore.QRect(10, 30, 161, 51))
        self.btnKeys2_mid.setObjectName("btnKeys2_mid")
        self.btnKeys2_high = QtWidgets.QPushButton(self.grbKeys2)
        self.btnKeys2_high.setGeometry(QtCore.QRect(190, 30, 161, 51))
        self.btnKeys2_high.setObjectName("btnKeys2_high")
        self.btnKeys2_bat = QtWidgets.QPushButton(self.grbKeys2)
        self.btnKeys2_bat.setGeometry(QtCore.QRect(10, 90, 161, 51))
        self.btnKeys2_bat.setObjectName("btnKeys2_bat")
        self.lneKeys2_bat = QtWidgets.QLineEdit(self.grbKeys2)
        self.lneKeys2_bat.setGeometry(QtCore.QRect(190, 90, 161, 51))
        self.lneKeys2_bat.setAlignment(QtCore.Qt.AlignCenter)
        self.lneKeys2_bat.setReadOnly(True)
        self.lneKeys2_bat.setObjectName("lneKeys2_bat")
        self.grbPer1 = QtWidgets.QGroupBox(self.centralWidget)
        self.grbPer1.setGeometry(QtCore.QRect(20, 290, 361, 551))
        self.grbPer1.setObjectName("grbPer1")
        self.btnPer1_temp = QtWidgets.QPushButton(self.grbPer1)
        self.btnPer1_temp.setGeometry(QtCore.QRect(10, 29, 161, 51))
        self.btnPer1_temp.setObjectName("btnPer1_temp")
        self.lnePer1_temp = QtWidgets.QLineEdit(self.grbPer1)
        self.lnePer1_temp.setGeometry(QtCore.QRect(190, 29, 161, 51))
        self.lnePer1_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.lnePer1_temp.setReadOnly(True)
        self.lnePer1_temp.setObjectName("lnePer1_temp")
        self.lnePer1_dig = QtWidgets.QLineEdit(self.grbPer1)
        self.lnePer1_dig.setGeometry(QtCore.QRect(10, 89, 161, 111))
        self.lnePer1_dig.setAlignment(QtCore.Qt.AlignCenter)
        self.lnePer1_dig.setObjectName("lnePer1_dig")
        self.btnPer1_dig_read = QtWidgets.QPushButton(self.grbPer1)
        self.btnPer1_dig_read.setGeometry(QtCore.QRect(190, 90, 161, 51))
        self.btnPer1_dig_read.setObjectName("btnPer1_dig_read")
        self.btnPer1_light = QtWidgets.QPushButton(self.grbPer1)
        self.btnPer1_light.setGeometry(QtCore.QRect(10, 210, 161, 51))
        self.btnPer1_light.setObjectName("btnPer1_light")
        self.lnePer1_light = QtWidgets.QLineEdit(self.grbPer1)
        self.lnePer1_light.setGeometry(QtCore.QRect(190, 210, 161, 51))
        self.lnePer1_light.setAlignment(QtCore.Qt.AlignCenter)
        self.lnePer1_light.setReadOnly(True)
        self.lnePer1_light.setObjectName("lnePer1_light")
        self.btnPer1_hum = QtWidgets.QPushButton(self.grbPer1)
        self.btnPer1_hum.setGeometry(QtCore.QRect(10, 270, 161, 51))
        self.btnPer1_hum.setObjectName("btnPer1_hum")
        self.lnePer1_hum = QtWidgets.QLineEdit(self.grbPer1)
        self.lnePer1_hum.setGeometry(QtCore.QRect(190, 270, 161, 51))
        self.lnePer1_hum.setText("")
        self.lnePer1_hum.setAlignment(QtCore.Qt.AlignCenter)
        self.lnePer1_hum.setReadOnly(True)
        self.lnePer1_hum.setObjectName("lnePer1_hum")
        self.lnePer1_alert = QtWidgets.QLineEdit(self.grbPer1)
        self.lnePer1_alert.setGeometry(QtCore.QRect(190, 329, 161, 51))
        self.lnePer1_alert.setAlignment(QtCore.Qt.AlignCenter)
        self.lnePer1_alert.setReadOnly(True)
        self.lnePer1_alert.setObjectName("lnePer1_alert")
        self.btnPer1_alert = QtWidgets.QPushButton(self.grbPer1)
        self.btnPer1_alert.setGeometry(QtCore.QRect(10, 329, 161, 51))
        self.btnPer1_alert.setObjectName("btnPer1_alert")
        self.btnPer1_led_on = QtWidgets.QPushButton(self.grbPer1)
        self.btnPer1_led_on.setGeometry(QtCore.QRect(10, 389, 161, 51))
        self.btnPer1_led_on.setObjectName("btnPer1_led_on")
        self.btnPer1_led_off = QtWidgets.QPushButton(self.grbPer1)
        self.btnPer1_led_off.setGeometry(QtCore.QRect(190, 390, 161, 51))
        self.btnPer1_led_off.setObjectName("btnPer1_led_off")
        self.lnePer1_but = QtWidgets.QLineEdit(self.grbPer1)
        self.lnePer1_but.setGeometry(QtCore.QRect(190, 449, 161, 51))
        self.lnePer1_but.setAlignment(QtCore.Qt.AlignCenter)
        self.lnePer1_but.setReadOnly(True)
        self.lnePer1_but.setObjectName("lnePer1_but")
        self.btnPer1_but = QtWidgets.QPushButton(self.grbPer1)
        self.btnPer1_but.setGeometry(QtCore.QRect(10, 449, 161, 51))
        self.btnPer1_but.setObjectName("btnPer1_but")
        self.btnPer1_dig_write = QtWidgets.QPushButton(self.grbPer1)
        self.btnPer1_dig_write.setGeometry(QtCore.QRect(190, 149, 161, 51))
        self.btnPer1_dig_write.setObjectName("btnPer1_dig_write")
        self.btnPer1_read_all = QtWidgets.QPushButton(self.grbPer1)
        self.btnPer1_read_all.setGeometry(QtCore.QRect(10, 510, 341, 31))
        self.btnPer1_read_all.setObjectName("btnPer1_read_all")
        self.grbPer2 = QtWidgets.QGroupBox(self.centralWidget)
        self.grbPer2.setGeometry(QtCore.QRect(410, 290, 361, 551))
        self.grbPer2.setObjectName("grbPer2")
        self.btnPer2_temp = QtWidgets.QPushButton(self.grbPer2)
        self.btnPer2_temp.setGeometry(QtCore.QRect(10, 30, 161, 51))
        self.btnPer2_temp.setObjectName("btnPer2_temp")
        self.lnePer2_temp = QtWidgets.QLineEdit(self.grbPer2)
        self.lnePer2_temp.setGeometry(QtCore.QRect(190, 30, 161, 51))
        self.lnePer2_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.lnePer2_temp.setReadOnly(True)
        self.lnePer2_temp.setObjectName("lnePer2_temp")
        self.lnePer2_dig = QtWidgets.QLineEdit(self.grbPer2)
        self.lnePer2_dig.setGeometry(QtCore.QRect(10, 90, 161, 111))
        self.lnePer2_dig.setAlignment(QtCore.Qt.AlignCenter)
        self.lnePer2_dig.setObjectName("lnePer2_dig")
        self.btnPer2_dig_read = QtWidgets.QPushButton(self.grbPer2)
        self.btnPer2_dig_read.setGeometry(QtCore.QRect(190, 91, 161, 51))
        self.btnPer2_dig_read.setObjectName("btnPer2_dig_read")
        self.btnPer2_light = QtWidgets.QPushButton(self.grbPer2)
        self.btnPer2_light.setGeometry(QtCore.QRect(10, 210, 161, 51))
        self.btnPer2_light.setObjectName("btnPer2_light")
        self.lnePer2_light = QtWidgets.QLineEdit(self.grbPer2)
        self.lnePer2_light.setGeometry(QtCore.QRect(190, 210, 161, 51))
        self.lnePer2_light.setAlignment(QtCore.Qt.AlignCenter)
        self.lnePer2_light.setReadOnly(True)
        self.lnePer2_light.setObjectName("lnePer2_light")
        self.btnPer2_hum = QtWidgets.QPushButton(self.grbPer2)
        self.btnPer2_hum.setGeometry(QtCore.QRect(10, 270, 161, 51))
        self.btnPer2_hum.setObjectName("btnPer2_hum")
        self.lnePer2_hum = QtWidgets.QLineEdit(self.grbPer2)
        self.lnePer2_hum.setGeometry(QtCore.QRect(190, 270, 161, 51))
        self.lnePer2_hum.setText("")
        self.lnePer2_hum.setAlignment(QtCore.Qt.AlignCenter)
        self.lnePer2_hum.setReadOnly(True)
        self.lnePer2_hum.setObjectName("lnePer2_hum")
        self.lnePer2_alert = QtWidgets.QLineEdit(self.grbPer2)
        self.lnePer2_alert.setGeometry(QtCore.QRect(190, 329, 161, 51))
        self.lnePer2_alert.setAlignment(QtCore.Qt.AlignCenter)
        self.lnePer2_alert.setReadOnly(True)
        self.lnePer2_alert.setObjectName("lnePer2_alert")
        self.btnPer2_alert = QtWidgets.QPushButton(self.grbPer2)
        self.btnPer2_alert.setGeometry(QtCore.QRect(10, 329, 161, 51))
        self.btnPer2_alert.setObjectName("btnPer2_alert")
        self.btnPer2_led_on = QtWidgets.QPushButton(self.grbPer2)
        self.btnPer2_led_on.setGeometry(QtCore.QRect(10, 389, 161, 51))
        self.btnPer2_led_on.setObjectName("btnPer2_led_on")
        self.btnPer2_led_off = QtWidgets.QPushButton(self.grbPer2)
        self.btnPer2_led_off.setGeometry(QtCore.QRect(190, 390, 161, 51))
        self.btnPer2_led_off.setObjectName("btnPer2_led_off")
        self.lnePer2_but = QtWidgets.QLineEdit(self.grbPer2)
        self.lnePer2_but.setGeometry(QtCore.QRect(190, 449, 161, 51))
        self.lnePer2_but.setAlignment(QtCore.Qt.AlignCenter)
        self.lnePer2_but.setReadOnly(True)
        self.lnePer2_but.setObjectName("lnePer2_but")
        self.btnPer2_but = QtWidgets.QPushButton(self.grbPer2)
        self.btnPer2_but.setGeometry(QtCore.QRect(10, 449, 161, 51))
        self.btnPer2_but.setObjectName("btnPer2_but")
        self.btnPer2_dig_write = QtWidgets.QPushButton(self.grbPer2)
        self.btnPer2_dig_write.setGeometry(QtCore.QRect(190, 150, 161, 51))
        self.btnPer2_dig_write.setObjectName("btnPer2_dig_write")
        self.btnPer2_read_all = QtWidgets.QPushButton(self.grbPer2)
        self.btnPer2_read_all.setGeometry(QtCore.QRect(10, 510, 341, 31))
        self.btnPer2_read_all.setObjectName("btnPer2_read_all")
        self.chbclosing_doors = QtWidgets.QCheckBox(self.centralWidget)
        self.chbclosing_doors.setGeometry(QtCore.QRect(260, 100, 381, 17))
        self.chbclosing_doors.setObjectName("chbclosing_doors")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 792, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSearchDevices.setText(_translate("MainWindow", "Search devices"))
        self.grbKeys1.setTitle(_translate("MainWindow", "Keys 1 (D9:D7:88:35:C4:F8)"))
        self.btnKeys1_mid.setText(_translate("MainWindow", "Mid Alert(0x01)"))
        self.btnKeys1_high.setText(_translate("MainWindow", "High Alert(0x02)"))
        self.btnKeys1_bat.setText(_translate("MainWindow", "Read\n"
"Battery level (0x2a19)"))
        self.grbKeys2.setTitle(_translate("MainWindow", "Keys 2 (E0:0E:F7:E4:6B:14)"))
        self.btnKeys2_mid.setText(_translate("MainWindow", "Mid Alert(0x01)"))
        self.btnKeys2_high.setText(_translate("MainWindow", "High Alert(0x02)"))
        self.btnKeys2_bat.setText(_translate("MainWindow", "Read\n"
"Battery level (0x2a19)"))
        self.grbPer1.setTitle(_translate("MainWindow", "Peripherial 1  (C1:44:EA:74:47:42)"))
        self.btnPer1_temp.setText(_translate("MainWindow", "Read\n"
"Temperature (0x2a6e)"))
        self.btnPer1_dig_read.setText(_translate("MainWindow", "Read\n"
"Digital (0x2a56)"))
        self.btnPer1_light.setText(_translate("MainWindow", "Read\n"
"Light Intensity (custom)"))
        self.btnPer1_hum.setText(_translate("MainWindow", "Read\n"
"Humidity (custom)"))
        self.btnPer1_alert.setText(_translate("MainWindow", "Read\n"
"New Alert (2a46)"))
        self.btnPer1_led_on.setText(_translate("MainWindow", "LED On (custom)"))
        self.btnPer1_led_off.setText(_translate("MainWindow", "LED Off (custom)"))
        self.btnPer1_but.setText(_translate("MainWindow", "Read\n"
"Button (custom)"))
        self.btnPer1_dig_write.setText(_translate("MainWindow", "Write\n"
"Digital (0x2a56)"))
        self.btnPer1_read_all.setText(_translate("MainWindow", "Read all characteristics"))
        self.grbPer2.setTitle(_translate("MainWindow", "Peripherial 2  (C5:03:B9:81:0B:D8)"))
        self.btnPer2_temp.setText(_translate("MainWindow", "Read\n"
"Temperature (0x2a6e)"))
        self.btnPer2_dig_read.setText(_translate("MainWindow", "Read\n"
"Digital (0x2a56)"))
        self.btnPer2_light.setText(_translate("MainWindow", "Read\n"
"Light Intensity (custom)"))
        self.btnPer2_hum.setText(_translate("MainWindow", "Read\n"
"Humidity (custom)"))
        self.btnPer2_alert.setText(_translate("MainWindow", "Read\n"
"New Alert (2a46)"))
        self.btnPer2_led_on.setText(_translate("MainWindow", "LED On (custom)"))
        self.btnPer2_led_off.setText(_translate("MainWindow", "LED Off (custom)"))
        self.btnPer2_but.setText(_translate("MainWindow", "Read\n"
"Button (custom)"))
        self.btnPer2_dig_write.setText(_translate("MainWindow", "Write\n"
"Digital (0x2a56)"))
        self.btnPer2_read_all.setText(_translate("MainWindow", "Read all characteristics"))
        self.chbclosing_doors.setText(_translate("MainWindow", "Closed door if least than two keys finded"))

