/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.4' (BDS version 1.1.3135.0) */

#include "service_if.h"
#include <stdint.h>
//#include "app_trace.h" 
#include "ble_security_system.h" 
#include "ble_home_controller.h" 
#include "nrf_temp.h"
#include "nrf_gpio.h"



static ble_security_system_t    m_security_system; 
static ble_home_controller_t    m_home_controller; 


void timer_handler(void * p_context)
{
    UNUSED_PARAMETER(p_context);
		ble_home_controller_light_controller_t p_light_controller;
		ble_home_controller_temperature_t p_temperature_controller;
		ble_security_system_door_controller_t  p_door_controller;
		ble_security_system_motions_sensor_t  p_sensors;
	
		//kontrola drzwi
		p_door_controller.door_close=(uint8_t)nrf_gpio_pin_read(22);
	
	  //temperatura
		int32_t volatile temperature;
		nrf_temp_init();
		temperature = (nrf_temp_read() / 4);	
		p_temperature_controller.temperature_value=	(uint32_t)temperature;		

		//oswietlenie
		uint8_t light_temp=0;
						for(int i=0;i<8;i++)
						{
							light_temp=light_temp+((uint8_t)nrf_gpio_pin_read(11+i)<<i);
						}
						p_light_controller.light=light_temp;
						
			
		//sensory ruchu
		p_sensors.sensor_1 =(uint8_t)nrf_gpio_pin_read(19);
		p_sensors.sensor_2=(uint8_t)nrf_gpio_pin_read(20);
					
		//wywolanie funkcji wysylajacych wartosc			
		ble_home_controller_light_controller_set(&m_home_controller,&p_light_controller);
	  ble_home_controller_temperature_controller_set(&m_home_controller,&p_temperature_controller);
		ble_security_system_door_controller_set(&m_security_system,&p_door_controller);
		ble_security_system_motions_sensor_set(&m_security_system, &p_sensors);
}



/**@brief Function for handling the Security_system events.
 *
 * @details This function will be called for all Security_system events which are passed to
 *          the application.
 *
 * @param[in]   p_security_system   Security_system structure.
 * @param[in]   p_evt   Event received from the Security_system.
 */



/**@brief Function for handling the Home_controller events.
 *
 * @details This function will be called for all Home_controller events which are passed to
 *          the application.
 *
 * @param[in]   p_home_controller   Home_controller structure.
 * @param[in]   p_evt   Event received from the Home_controller.
 */


		//nasze funkcje
		//tylko odczyt, zapis raczej nie poniewaz nie mozemy wpisac tego co tu mamy dalej

static void ble_security_system_evt_handler(ble_security_system_t * p_security_system, ble_security_system_evt_t * p_evt)
{
			ble_security_system_evt_t temporary=*p_evt;
			uint8_t lock;
			lock = temporary.params.door_lock.d_lock;
			if(lock!=0) nrf_gpio_pin_set(23);
			else nrf_gpio_pin_clear(23);
	
	
}

static void ble_home_controller_evt_handler(ble_home_controller_t * p_home_controller, ble_home_controller_evt_t * p_evt)
{	
		uint8_t light;
		uint8_t maska=1;
		int i;
		ble_home_controller_evt_t temporary =*p_evt;	
		light = temporary.params.light_controller.light;	
				//swiatlo jest wektorem 8 elementowym gdzie kazdemu swiatlu odpowiada jeden bit
				//wyjscia od 11 do 18   
				for(i=0;i<8;i++){	
					if((light&maska)==maska)
					{
						nrf_gpio_pin_set(11+i);
					}
					else 
					{
						nrf_gpio_pin_clear(11+i);
					}
					maska=maska<<1;
				}
}


/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t bluetooth_init(void)
{
	
    uint32_t    err_code; 
    ble_security_system_init_t    security_system_init; 
    ble_home_controller_init_t    home_controller_init; 
    
		
								//nasza mmodyfikacja 
									security_system_init.evt_handler=ble_security_system_evt_handler;
									home_controller_init.evt_handler=ble_home_controller_evt_handler;
	
	
    // Initialize Security_system.
    memset(&security_system_init, 0, sizeof(security_system_init));

   
    memset(&security_system_init.ble_security_system_motions_sensor_initial_value.sensor_1,
           0x00,
           sizeof(security_system_init.ble_security_system_motions_sensor_initial_value.sensor_1));
    memset(&security_system_init.ble_security_system_motions_sensor_initial_value.sensor_1_time,
           0x00,
           sizeof(security_system_init.ble_security_system_motions_sensor_initial_value.sensor_1_time));
    memset(&security_system_init.ble_security_system_motions_sensor_initial_value.sensor_2,
           0x00,
           sizeof(security_system_init.ble_security_system_motions_sensor_initial_value.sensor_2));
    memset(&security_system_init.ble_security_system_motions_sensor_initial_value.sensor_2_time,
           0x00,
           sizeof(security_system_init.ble_security_system_motions_sensor_initial_value.sensor_2_time));
    memset(&security_system_init.ble_security_system_door_controller_initial_value.door_close,
           0x00,
           sizeof(security_system_init.ble_security_system_door_controller_initial_value.door_close));
    memset(&security_system_init.ble_security_system_door_lock_initial_value.d_lock,
           0x00,
           sizeof(security_system_init.ble_security_system_door_lock_initial_value.d_lock));

    err_code = ble_security_system_init(&m_security_system, &security_system_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Initialize Home_controller.
    memset(&home_controller_init, 0, sizeof(home_controller_init));

    //home_controller_init.evt_handler = on_home_controller_evt; 
    memset(&home_controller_init.ble_home_controller_temperature_initial_value.temperature_value,
           0x00,
           sizeof(home_controller_init.ble_home_controller_temperature_initial_value.temperature_value));
    memset(&home_controller_init.ble_home_controller_light_controller_initial_value.light,
           0x00,
           sizeof(home_controller_init.ble_home_controller_light_controller_initial_value.light));

    err_code = ble_home_controller_init(&m_home_controller, &home_controller_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 
		
		
    return NRF_SUCCESS;
}

/**@brief Function for handling the Application's BLE Stack events.
 *
 * @details Handles all events from the BLE stack of interest to all Bluetooth Developer Studio generated Services.
 *
 * @param[in]   p_ble_evt  Event received from the BLE stack.
 */
void bluetooth_on_ble_evt(ble_evt_t * p_ble_evt)
{ 
    ble_security_system_on_ble_evt(&m_security_system, p_ble_evt); 
    ble_home_controller_on_ble_evt(&m_home_controller, p_ble_evt); 
}
