
/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.4' (BDS version 1.1.3135.0) */
#include "boards.h"
#include "nrf_delay.h"
#include "service_if.h"
#include <stdint.h>
//#include "app_trace.h" 
#include "ble_home_controller.h" 
#include "ble_security_system.h" 
#include "nrf_temp.h"
#include "nrf_soc.h"
#include "nrf_log.h"

static ble_home_controller_t    m_home_controller; 
static ble_security_system_t    m_security_system; 

uint8_t light_memory;
uint8_t timer_memory;

void light_set(uint8_t light)
{
		bsp_board_leds_off();
		if ((light&1)==1)bsp_board_led_on(0);
		if ((light&2)==2)bsp_board_led_on(1);
		if ((light&4)==4)bsp_board_led_on(2);
		if ((light&8)==8)bsp_board_led_on(3);
}	
void timer_handler_button(void * p_context)
{	
		UNUSED_PARAMETER(p_context);
		if(bsp_board_button_state_get((uint32_t)3))
		{		
				if (timer_memory==0) light_memory=light_memory+1;
				timer_memory=1;
		}
		if (light_memory>15) light_memory=0;
	
}
void timer_handler(void * p_context)
{	
    UNUSED_PARAMETER(p_context);
		int32_t temperature;
		ble_home_controller_temperature_t p_temperature_controller;
		ble_home_controller_light_controller_t p_light_controller;
		ble_security_system_move_sensors_t  p_move_sensors;
	
	
    sd_temp_get(&temperature);
		nrf_delay_ms(60);
		temperature=temperature/4;
		p_temperature_controller.temperature_value=	(uint32_t)temperature;		
		p_light_controller.light=light_memory;
	  light_set(light_memory);
		timer_memory=0;
	  ble_home_controller_temperature_set(&m_home_controller,&p_temperature_controller);
		ble_home_controller_light_controller_set(&m_home_controller,&p_light_controller);
	
		p_move_sensors.sensor_2=100;
		p_move_sensors.sensor_1=15;
		ble_security_system_move_sensors_set(&m_security_system,&p_move_sensors);
}

/**@brief Function for handling the Home_controller events.
 *
 * @details This function will be called for all Home_controller events which are passed to
 *          the application.
 *
 * @param[in]   p_home_controller   Home_controller structure.
 * @param[in]   p_evt   Event received from the Home_controller.
 */
static void on_home_controller_evt(ble_home_controller_t * p_home_controller, ble_home_controller_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        case BLE_HOME_CONTROLLER_LIGHT_CONTROLLER_EVT_WRITE:
						light_memory=p_evt->params.light_controller.light;
						light_set(p_evt->params.light_controller.light);
            //app_trace_log("[Bluetooth_IF]: HOME_CONTROLLER_LIGHT_CONTROLLER evt WRITE. \r\n");
            break; 
        default:
            // No implementation needed.
            break;
    }
}

static void on_security_system_evt(ble_security_system_t * p_security_system, ble_security_system_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        case BLE_SECURITY_SYSTEM_DOOR_LOCK_EVT_WRITE:
            //app_trace_log("[Bluetooth_IF]: SECURITY_SYSTEM_DOOR_LOCK evt WRITE. \r\n");
            break; 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t bluetooth_init(void)
{
    uint32_t    err_code; 
    ble_home_controller_init_t    home_controller_init; 
    ble_security_system_init_t    security_system_init; 
    

    // Initialize Home_controller.
    memset(&home_controller_init, 0, sizeof(home_controller_init));

    home_controller_init.evt_handler = on_home_controller_evt; 
    memset(&home_controller_init.ble_home_controller_temperature_initial_value.temperature_value,
           0x00,
           sizeof(home_controller_init.ble_home_controller_temperature_initial_value.temperature_value));
    memset(&home_controller_init.ble_home_controller_light_controller_initial_value.light,
           0x00,
           sizeof(home_controller_init.ble_home_controller_light_controller_initial_value.light));

    err_code = ble_home_controller_init(&m_home_controller, &home_controller_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Initialize security_system.
    memset(&security_system_init, 0, sizeof(security_system_init));

    security_system_init.evt_handler = on_security_system_evt; 
    memset(&security_system_init.ble_security_system_move_sensors_initial_value.sensor_1,
           0x00,
           sizeof(security_system_init.ble_security_system_move_sensors_initial_value.sensor_1));
    memset(&security_system_init.ble_security_system_move_sensors_initial_value.sensor_2,
           0x00,
           sizeof(security_system_init.ble_security_system_move_sensors_initial_value.sensor_2));
    memset(&security_system_init.ble_security_system_door_lock_initial_value.door_closed,
           0x00,
           sizeof(security_system_init.ble_security_system_door_lock_initial_value.door_closed));
    memset(&security_system_init.ble_security_system_door_controller_initial_value.door_control,
           0x00,
           sizeof(security_system_init.ble_security_system_door_controller_initial_value.door_control));

    err_code = ble_security_system_init(&m_security_system, &security_system_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for handling the Application's BLE Stack events.
 *
 * @details Handles all events from the BLE stack of interest to all Bluetooth Developer Studio generated Services.
 *
 * @param[in]   p_ble_evt  Event received from the BLE stack.
 */
void bluetooth_on_ble_evt(ble_evt_t * p_ble_evt)
{ 
    ble_home_controller_on_ble_evt(&m_home_controller, p_ble_evt); 
    ble_security_system_on_ble_evt(&m_security_system, p_ble_evt); 
}
